/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TRE.Rest.Client.Client.OpenAPIDateConverter;

namespace TRE.Rest.Client.Model
{
    /// <summary>
    /// ResourceTemplateInformationInList
    /// </summary>
    [DataContract(Name = "ResourceTemplateInformationInList")]
    public partial class ResourceTemplateInformationInList : IEquatable<ResourceTemplateInformationInList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceTemplateInformationInList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResourceTemplateInformationInList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceTemplateInformationInList" /> class.
        /// </summary>
        /// <param name="templates">templates (required).</param>
        public ResourceTemplateInformationInList(Collection<ResourceTemplateInformation> templates = default(Collection<ResourceTemplateInformation>))
        {
            // to ensure "templates" is required (not null)
            if (templates == null) {
                throw new ArgumentNullException("templates is a required property for ResourceTemplateInformationInList and cannot be null");
            }
            this.Templates = templates;
        }

        /// <summary>
        /// Gets or Sets Templates
        /// </summary>
        [DataMember(Name = "templates", IsRequired = true, EmitDefaultValue = false)]
        public Collection<ResourceTemplateInformation> Templates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResourceTemplateInformationInList {\n");
            sb.Append("  Templates: ").Append(Templates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResourceTemplateInformationInList);
        }

        /// <summary>
        /// Returns true if ResourceTemplateInformationInList instances are equal
        /// </summary>
        /// <param name="input">Instance of ResourceTemplateInformationInList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResourceTemplateInformationInList input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Templates == input.Templates ||
                    this.Templates != null &&
                    input.Templates != null &&
                    this.Templates.SequenceEqual(input.Templates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Templates != null)
                {
                    hashCode = (hashCode * 59) + this.Templates.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
