/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TRE.Rest.Client.Client.OpenAPIDateConverter;

namespace TRE.Rest.Client.Model
{
    /// <summary>
    /// Type of resource to deploy
    /// </summary>
    /// <value>Type of resource to deploy</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ResourceType
    {
        /// <summary>
        /// Enum Workspace for value: workspace
        /// </summary>
        [EnumMember(Value = "workspace")]
        Workspace = 1,

        /// <summary>
        /// Enum WorkspaceService for value: workspace-service
        /// </summary>
        [EnumMember(Value = "workspace-service")]
        WorkspaceService = 2,

        /// <summary>
        /// Enum UserResource for value: user-resource
        /// </summary>
        [EnumMember(Value = "user-resource")]
        UserResource = 3,

        /// <summary>
        /// Enum SharedService for value: shared-service
        /// </summary>
        [EnumMember(Value = "shared-service")]
        SharedService = 4

    }

}
