/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TRE.Rest.Client.Client.OpenAPIDateConverter;

namespace TRE.Rest.Client.Model
{
    /// <summary>
    /// SharedServicesInList
    /// </summary>
    [DataContract(Name = "SharedServicesInList")]
    public partial class SharedServicesInList : IEquatable<SharedServicesInList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SharedServicesInList" /> class.
        /// </summary>
        /// <param name="sharedServices">sharedServices.</param>
        public SharedServicesInList(Collection<SharedService> sharedServices = default(Collection<SharedService>))
        {
            this.SharedServices = sharedServices;
        }

        /// <summary>
        /// Gets or Sets SharedServices
        /// </summary>
        [DataMember(Name = "sharedServices", EmitDefaultValue = false)]
        public Collection<SharedService> SharedServices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SharedServicesInList {\n");
            sb.Append("  SharedServices: ").Append(SharedServices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SharedServicesInList);
        }

        /// <summary>
        /// Returns true if SharedServicesInList instances are equal
        /// </summary>
        /// <param name="input">Instance of SharedServicesInList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SharedServicesInList input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SharedServices == input.SharedServices ||
                    this.SharedServices != null &&
                    input.SharedServices != null &&
                    this.SharedServices.SequenceEqual(input.SharedServices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SharedServices != null)
                {
                    hashCode = (hashCode * 59) + this.SharedServices.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
