/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TRE.Rest.Client.Client.OpenAPIDateConverter;

namespace TRE.Rest.Client.Model
{
    /// <summary>
    /// WorkspaceInResponse
    /// </summary>
    [DataContract(Name = "WorkspaceInResponse")]
    public partial class WorkspaceInResponse : IEquatable<WorkspaceInResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceInResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkspaceInResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceInResponse" /> class.
        /// </summary>
        /// <param name="workspace">workspace (required).</param>
        public WorkspaceInResponse(Workspace workspace = default(Workspace))
        {
            // to ensure "workspace" is required (not null)
            if (workspace == null) {
                throw new ArgumentNullException("workspace is a required property for WorkspaceInResponse and cannot be null");
            }
            this.Workspace = workspace;
        }

        /// <summary>
        /// Gets or Sets Workspace
        /// </summary>
        [DataMember(Name = "workspace", IsRequired = true, EmitDefaultValue = false)]
        public Workspace Workspace { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkspaceInResponse {\n");
            sb.Append("  Workspace: ").Append(Workspace).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkspaceInResponse);
        }

        /// <summary>
        /// Returns true if WorkspaceInResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkspaceInResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkspaceInResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Workspace == input.Workspace ||
                    (this.Workspace != null &&
                    this.Workspace.Equals(input.Workspace))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Workspace != null)
                {
                    hashCode = (hashCode * 59) + this.Workspace.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
