/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using TRE.Rest.Client.Client;
using TRE.Rest.Client.Model;

namespace TRE.Rest.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharedServiceTemplatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Shared Service Template By Name
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <returns>SharedServiceTemplateInResponse</returns>
        SharedServiceTemplateInResponse GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGet(string sharedServiceTemplateName);

        /// <summary>
        /// Get Shared Service Template By Name
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <returns>ApiResponse of SharedServiceTemplateInResponse</returns>
        ApiResponse<SharedServiceTemplateInResponse> GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetWithHttpInfo(string sharedServiceTemplateName);
        /// <summary>
        /// Get Shared Service Templates
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ResourceTemplateInformationInList</returns>
        ResourceTemplateInformationInList GetSharedServiceTemplatesApiSharedServiceTemplatesGet();

        /// <summary>
        /// Get Shared Service Templates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ResourceTemplateInformationInList</returns>
        ApiResponse<ResourceTemplateInformationInList> GetSharedServiceTemplatesApiSharedServiceTemplatesGetWithHttpInfo();
        /// <summary>
        /// Register Shared Service Template
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <returns>SharedServiceTemplateInResponse</returns>
        SharedServiceTemplateInResponse RegisterSharedServiceTemplateApiSharedServiceTemplatesPost(SharedServiceTemplateInCreate sharedServiceTemplateInCreate);

        /// <summary>
        /// Register Shared Service Template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <returns>ApiResponse of SharedServiceTemplateInResponse</returns>
        ApiResponse<SharedServiceTemplateInResponse> RegisterSharedServiceTemplateApiSharedServiceTemplatesPostWithHttpInfo(SharedServiceTemplateInCreate sharedServiceTemplateInCreate);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharedServiceTemplatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Shared Service Template By Name
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedServiceTemplateInResponse</returns>
        System.Threading.Tasks.Task<SharedServiceTemplateInResponse> GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetAsync(string sharedServiceTemplateName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Shared Service Template By Name
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedServiceTemplateInResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SharedServiceTemplateInResponse>> GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetWithHttpInfoAsync(string sharedServiceTemplateName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Shared Service Templates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ResourceTemplateInformationInList</returns>
        System.Threading.Tasks.Task<ResourceTemplateInformationInList> GetSharedServiceTemplatesApiSharedServiceTemplatesGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Shared Service Templates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ResourceTemplateInformationInList)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResourceTemplateInformationInList>> GetSharedServiceTemplatesApiSharedServiceTemplatesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Register Shared Service Template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedServiceTemplateInResponse</returns>
        System.Threading.Tasks.Task<SharedServiceTemplateInResponse> RegisterSharedServiceTemplateApiSharedServiceTemplatesPostAsync(SharedServiceTemplateInCreate sharedServiceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Register Shared Service Template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedServiceTemplateInResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SharedServiceTemplateInResponse>> RegisterSharedServiceTemplateApiSharedServiceTemplatesPostWithHttpInfoAsync(SharedServiceTemplateInCreate sharedServiceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISharedServiceTemplatesApi : ISharedServiceTemplatesApiSync, ISharedServiceTemplatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SharedServiceTemplatesApi : ISharedServiceTemplatesApi
    {
        private TRE.Rest.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedServiceTemplatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SharedServiceTemplatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedServiceTemplatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SharedServiceTemplatesApi(string basePath)
        {
            this.Configuration = TRE.Rest.Client.Client.Configuration.MergeConfigurations(
                TRE.Rest.Client.Client.GlobalConfiguration.Instance,
                new TRE.Rest.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = TRE.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedServiceTemplatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SharedServiceTemplatesApi(TRE.Rest.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TRE.Rest.Client.Client.Configuration.MergeConfigurations(
                TRE.Rest.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = TRE.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SharedServiceTemplatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SharedServiceTemplatesApi(TRE.Rest.Client.Client.ISynchronousClient client, TRE.Rest.Client.Client.IAsynchronousClient asyncClient, TRE.Rest.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TRE.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TRE.Rest.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TRE.Rest.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TRE.Rest.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TRE.Rest.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Shared Service Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <returns>SharedServiceTemplateInResponse</returns>
        public SharedServiceTemplateInResponse GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGet(string sharedServiceTemplateName)
        {
            TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse> localVarResponse = GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetWithHttpInfo(sharedServiceTemplateName);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Shared Service Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <returns>ApiResponse of SharedServiceTemplateInResponse</returns>
        public TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse> GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetWithHttpInfo(string sharedServiceTemplateName)
        {
            // verify the required parameter 'sharedServiceTemplateName' is set
            if (sharedServiceTemplateName == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'sharedServiceTemplateName' when calling SharedServiceTemplatesApi->GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGet");
            }

            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("shared_service_template_name", TRE.Rest.Client.Client.ClientUtils.ParameterToString(sharedServiceTemplateName)); // path parameter

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SharedServiceTemplateInResponse>("/api/shared-service-templates/{shared_service_template_name}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Shared Service Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedServiceTemplateInResponse</returns>
        public async System.Threading.Tasks.Task<SharedServiceTemplateInResponse> GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetAsync(string sharedServiceTemplateName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse> localVarResponse = await GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetWithHttpInfoAsync(sharedServiceTemplateName, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Shared Service Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateName"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedServiceTemplateInResponse)</returns>
        public async System.Threading.Tasks.Task<TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse>> GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGetWithHttpInfoAsync(string sharedServiceTemplateName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'sharedServiceTemplateName' is set
            if (sharedServiceTemplateName == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'sharedServiceTemplateName' when calling SharedServiceTemplatesApi->GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGet");
            }


            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("shared_service_template_name", TRE.Rest.Client.Client.ClientUtils.ParameterToString(sharedServiceTemplateName)); // path parameter

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SharedServiceTemplateInResponse>("/api/shared-service-templates/{shared_service_template_name}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedServiceTemplateByNameApiSharedServiceTemplatesSharedServiceTemplateNameGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Shared Service Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ResourceTemplateInformationInList</returns>
        public ResourceTemplateInformationInList GetSharedServiceTemplatesApiSharedServiceTemplatesGet()
        {
            TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList> localVarResponse = GetSharedServiceTemplatesApiSharedServiceTemplatesGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Shared Service Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ResourceTemplateInformationInList</returns>
        public TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList> GetSharedServiceTemplatesApiSharedServiceTemplatesGetWithHttpInfo()
        {
            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ResourceTemplateInformationInList>("/api/shared-service-templates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedServiceTemplatesApiSharedServiceTemplatesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Shared Service Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ResourceTemplateInformationInList</returns>
        public async System.Threading.Tasks.Task<ResourceTemplateInformationInList> GetSharedServiceTemplatesApiSharedServiceTemplatesGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList> localVarResponse = await GetSharedServiceTemplatesApiSharedServiceTemplatesGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Shared Service Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ResourceTemplateInformationInList)</returns>
        public async System.Threading.Tasks.Task<TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList>> GetSharedServiceTemplatesApiSharedServiceTemplatesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ResourceTemplateInformationInList>("/api/shared-service-templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSharedServiceTemplatesApiSharedServiceTemplatesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Register Shared Service Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <returns>SharedServiceTemplateInResponse</returns>
        public SharedServiceTemplateInResponse RegisterSharedServiceTemplateApiSharedServiceTemplatesPost(SharedServiceTemplateInCreate sharedServiceTemplateInCreate)
        {
            TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse> localVarResponse = RegisterSharedServiceTemplateApiSharedServiceTemplatesPostWithHttpInfo(sharedServiceTemplateInCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Register Shared Service Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <returns>ApiResponse of SharedServiceTemplateInResponse</returns>
        public TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse> RegisterSharedServiceTemplateApiSharedServiceTemplatesPostWithHttpInfo(SharedServiceTemplateInCreate sharedServiceTemplateInCreate)
        {
            // verify the required parameter 'sharedServiceTemplateInCreate' is set
            if (sharedServiceTemplateInCreate == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'sharedServiceTemplateInCreate' when calling SharedServiceTemplatesApi->RegisterSharedServiceTemplateApiSharedServiceTemplatesPost");
            }

            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = sharedServiceTemplateInCreate;

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SharedServiceTemplateInResponse>("/api/shared-service-templates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RegisterSharedServiceTemplateApiSharedServiceTemplatesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Register Shared Service Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SharedServiceTemplateInResponse</returns>
        public async System.Threading.Tasks.Task<SharedServiceTemplateInResponse> RegisterSharedServiceTemplateApiSharedServiceTemplatesPostAsync(SharedServiceTemplateInCreate sharedServiceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse> localVarResponse = await RegisterSharedServiceTemplateApiSharedServiceTemplatesPostWithHttpInfoAsync(sharedServiceTemplateInCreate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Register Shared Service Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sharedServiceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SharedServiceTemplateInResponse)</returns>
        public async System.Threading.Tasks.Task<TRE.Rest.Client.Client.ApiResponse<SharedServiceTemplateInResponse>> RegisterSharedServiceTemplateApiSharedServiceTemplatesPostWithHttpInfoAsync(SharedServiceTemplateInCreate sharedServiceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'sharedServiceTemplateInCreate' is set
            if (sharedServiceTemplateInCreate == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'sharedServiceTemplateInCreate' when calling SharedServiceTemplatesApi->RegisterSharedServiceTemplateApiSharedServiceTemplatesPost");
            }


            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = sharedServiceTemplateInCreate;

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SharedServiceTemplateInResponse>("/api/shared-service-templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RegisterSharedServiceTemplateApiSharedServiceTemplatesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
