/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using TRE.Rest.Client.Client;
using TRE.Rest.Client.Model;

namespace TRE.Rest.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspaceTemplatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Workspace Template By Name
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <returns>WorkspaceTemplateInResponse</returns>
        WorkspaceTemplateInResponse GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet(string workspaceTemplateName, bool? isUpdate = default(bool?));

        /// <summary>
        /// Get Workspace Template By Name
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <returns>ApiResponse of WorkspaceTemplateInResponse</returns>
        ApiResponse<WorkspaceTemplateInResponse> GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetWithHttpInfo(string workspaceTemplateName, bool? isUpdate = default(bool?));
        /// <summary>
        /// Get Workspace Templates
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ResourceTemplateInformationInList</returns>
        ResourceTemplateInformationInList GetWorkspaceTemplatesApiWorkspaceTemplatesGet();

        /// <summary>
        /// Get Workspace Templates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ResourceTemplateInformationInList</returns>
        ApiResponse<ResourceTemplateInformationInList> GetWorkspaceTemplatesApiWorkspaceTemplatesGetWithHttpInfo();
        /// <summary>
        /// Register Workspace Template
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <returns>WorkspaceTemplateInResponse</returns>
        WorkspaceTemplateInResponse RegisterWorkspaceTemplateApiWorkspaceTemplatesPost(WorkspaceTemplateInCreate workspaceTemplateInCreate);

        /// <summary>
        /// Register Workspace Template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <returns>ApiResponse of WorkspaceTemplateInResponse</returns>
        ApiResponse<WorkspaceTemplateInResponse> RegisterWorkspaceTemplateApiWorkspaceTemplatesPostWithHttpInfo(WorkspaceTemplateInCreate workspaceTemplateInCreate);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspaceTemplatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Workspace Template By Name
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WorkspaceTemplateInResponse</returns>
        System.Threading.Tasks.Task<WorkspaceTemplateInResponse> GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetAsync(string workspaceTemplateName, bool? isUpdate = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Workspace Template By Name
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WorkspaceTemplateInResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<WorkspaceTemplateInResponse>> GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetWithHttpInfoAsync(string workspaceTemplateName, bool? isUpdate = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Workspace Templates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ResourceTemplateInformationInList</returns>
        System.Threading.Tasks.Task<ResourceTemplateInformationInList> GetWorkspaceTemplatesApiWorkspaceTemplatesGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Workspace Templates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ResourceTemplateInformationInList)</returns>
        System.Threading.Tasks.Task<ApiResponse<ResourceTemplateInformationInList>> GetWorkspaceTemplatesApiWorkspaceTemplatesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Register Workspace Template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WorkspaceTemplateInResponse</returns>
        System.Threading.Tasks.Task<WorkspaceTemplateInResponse> RegisterWorkspaceTemplateApiWorkspaceTemplatesPostAsync(WorkspaceTemplateInCreate workspaceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Register Workspace Template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WorkspaceTemplateInResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<WorkspaceTemplateInResponse>> RegisterWorkspaceTemplateApiWorkspaceTemplatesPostWithHttpInfoAsync(WorkspaceTemplateInCreate workspaceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspaceTemplatesApi : IWorkspaceTemplatesApiSync, IWorkspaceTemplatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WorkspaceTemplatesApi : IWorkspaceTemplatesApi
    {
        private TRE.Rest.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceTemplatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WorkspaceTemplatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceTemplatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WorkspaceTemplatesApi(string basePath)
        {
            this.Configuration = TRE.Rest.Client.Client.Configuration.MergeConfigurations(
                TRE.Rest.Client.Client.GlobalConfiguration.Instance,
                new TRE.Rest.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = TRE.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceTemplatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WorkspaceTemplatesApi(TRE.Rest.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TRE.Rest.Client.Client.Configuration.MergeConfigurations(
                TRE.Rest.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new TRE.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = TRE.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceTemplatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WorkspaceTemplatesApi(TRE.Rest.Client.Client.ISynchronousClient client, TRE.Rest.Client.Client.IAsynchronousClient asyncClient, TRE.Rest.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TRE.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TRE.Rest.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TRE.Rest.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TRE.Rest.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TRE.Rest.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Workspace Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <returns>WorkspaceTemplateInResponse</returns>
        public WorkspaceTemplateInResponse GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet(string workspaceTemplateName, bool? isUpdate = default(bool?))
        {
            TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse> localVarResponse = GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetWithHttpInfo(workspaceTemplateName, isUpdate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Workspace Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <returns>ApiResponse of WorkspaceTemplateInResponse</returns>
        public TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse> GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetWithHttpInfo(string workspaceTemplateName, bool? isUpdate = default(bool?))
        {
            // verify the required parameter 'workspaceTemplateName' is set
            if (workspaceTemplateName == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'workspaceTemplateName' when calling WorkspaceTemplatesApi->GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet");
            }

            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("workspace_template_name", TRE.Rest.Client.Client.ClientUtils.ParameterToString(workspaceTemplateName)); // path parameter
            if (isUpdate != null)
            {
                localVarRequestOptions.QueryParameters.Add(TRE.Rest.Client.Client.ClientUtils.ParameterToMultiMap("", "is_update", isUpdate));
            }

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<WorkspaceTemplateInResponse>("/api/workspace-templates/{workspace_template_name}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Workspace Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WorkspaceTemplateInResponse</returns>
        public async System.Threading.Tasks.Task<WorkspaceTemplateInResponse> GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetAsync(string workspaceTemplateName, bool? isUpdate = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse> localVarResponse = await GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetWithHttpInfoAsync(workspaceTemplateName, isUpdate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Workspace Template By Name 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateName"></param>
        /// <param name="isUpdate"> (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WorkspaceTemplateInResponse)</returns>
        public async System.Threading.Tasks.Task<TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse>> GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetWithHttpInfoAsync(string workspaceTemplateName, bool? isUpdate = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'workspaceTemplateName' is set
            if (workspaceTemplateName == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'workspaceTemplateName' when calling WorkspaceTemplatesApi->GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet");
            }


            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("workspace_template_name", TRE.Rest.Client.Client.ClientUtils.ParameterToString(workspaceTemplateName)); // path parameter
            if (isUpdate != null)
            {
                localVarRequestOptions.QueryParameters.Add(TRE.Rest.Client.Client.ClientUtils.ParameterToMultiMap("", "is_update", isUpdate));
            }

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<WorkspaceTemplateInResponse>("/api/workspace-templates/{workspace_template_name}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Workspace Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ResourceTemplateInformationInList</returns>
        public ResourceTemplateInformationInList GetWorkspaceTemplatesApiWorkspaceTemplatesGet()
        {
            TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList> localVarResponse = GetWorkspaceTemplatesApiWorkspaceTemplatesGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Workspace Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ResourceTemplateInformationInList</returns>
        public TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList> GetWorkspaceTemplatesApiWorkspaceTemplatesGetWithHttpInfo()
        {
            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ResourceTemplateInformationInList>("/api/workspace-templates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWorkspaceTemplatesApiWorkspaceTemplatesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Workspace Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ResourceTemplateInformationInList</returns>
        public async System.Threading.Tasks.Task<ResourceTemplateInformationInList> GetWorkspaceTemplatesApiWorkspaceTemplatesGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList> localVarResponse = await GetWorkspaceTemplatesApiWorkspaceTemplatesGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Workspace Templates 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ResourceTemplateInformationInList)</returns>
        public async System.Threading.Tasks.Task<TRE.Rest.Client.Client.ApiResponse<ResourceTemplateInformationInList>> GetWorkspaceTemplatesApiWorkspaceTemplatesGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ResourceTemplateInformationInList>("/api/workspace-templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWorkspaceTemplatesApiWorkspaceTemplatesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Register Workspace Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <returns>WorkspaceTemplateInResponse</returns>
        public WorkspaceTemplateInResponse RegisterWorkspaceTemplateApiWorkspaceTemplatesPost(WorkspaceTemplateInCreate workspaceTemplateInCreate)
        {
            TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse> localVarResponse = RegisterWorkspaceTemplateApiWorkspaceTemplatesPostWithHttpInfo(workspaceTemplateInCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Register Workspace Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <returns>ApiResponse of WorkspaceTemplateInResponse</returns>
        public TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse> RegisterWorkspaceTemplateApiWorkspaceTemplatesPostWithHttpInfo(WorkspaceTemplateInCreate workspaceTemplateInCreate)
        {
            // verify the required parameter 'workspaceTemplateInCreate' is set
            if (workspaceTemplateInCreate == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'workspaceTemplateInCreate' when calling WorkspaceTemplatesApi->RegisterWorkspaceTemplateApiWorkspaceTemplatesPost");
            }

            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = workspaceTemplateInCreate;

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<WorkspaceTemplateInResponse>("/api/workspace-templates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RegisterWorkspaceTemplateApiWorkspaceTemplatesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Register Workspace Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WorkspaceTemplateInResponse</returns>
        public async System.Threading.Tasks.Task<WorkspaceTemplateInResponse> RegisterWorkspaceTemplateApiWorkspaceTemplatesPostAsync(WorkspaceTemplateInCreate workspaceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse> localVarResponse = await RegisterWorkspaceTemplateApiWorkspaceTemplatesPostWithHttpInfoAsync(workspaceTemplateInCreate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Register Workspace Template 
        /// </summary>
        /// <exception cref="TRE.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="workspaceTemplateInCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WorkspaceTemplateInResponse)</returns>
        public async System.Threading.Tasks.Task<TRE.Rest.Client.Client.ApiResponse<WorkspaceTemplateInResponse>> RegisterWorkspaceTemplateApiWorkspaceTemplatesPostWithHttpInfoAsync(WorkspaceTemplateInCreate workspaceTemplateInCreate, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'workspaceTemplateInCreate' is set
            if (workspaceTemplateInCreate == null)
            {
                throw new TRE.Rest.Client.Client.ApiException(400, "Missing required parameter 'workspaceTemplateInCreate' when calling WorkspaceTemplatesApi->RegisterWorkspaceTemplateApiWorkspaceTemplatesPost");
            }


            TRE.Rest.Client.Client.RequestOptions localVarRequestOptions = new TRE.Rest.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TRE.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = TRE.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = workspaceTemplateInCreate;

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<WorkspaceTemplateInResponse>("/api/workspace-templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RegisterWorkspaceTemplateApiWorkspaceTemplatesPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
