/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TRE.Rest.Client.Client;
using TRE.Rest.Client.Api;
// uncomment below to import models
//using TRE.Rest.Client.Model;

namespace TRE.Rest.Client.Test.Api
{
    /// <summary>
    ///  Class for testing UserResourceTemplatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserResourceTemplatesApiTests : IDisposable
    {
        private UserResourceTemplatesApi instance;

        public UserResourceTemplatesApiTests()
        {
            instance = new UserResourceTemplatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserResourceTemplatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UserResourceTemplatesApi
            //Assert.IsType<UserResourceTemplatesApi>(instance);
        }

        /// <summary>
        /// Test GetUserResourceTemplateByNameAndWorkspaceServiceApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesUserResourceTemplateNameGet
        /// </summary>
        [Fact]
        public void GetUserResourceTemplateByNameAndWorkspaceServiceApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesUserResourceTemplateNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceTemplateName = null;
            //string userResourceTemplateName = null;
            //bool? isUpdate = null;
            //var response = instance.GetUserResourceTemplateByNameAndWorkspaceServiceApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesUserResourceTemplateNameGet(serviceTemplateName, userResourceTemplateName, isUpdate);
            //Assert.IsType<UserResourceTemplateInResponse>(response);
        }

        /// <summary>
        /// Test GetUserResourceTemplatesApplicableToTheWorkspaceServiceTemplateApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesGet
        /// </summary>
        [Fact]
        public void GetUserResourceTemplatesApplicableToTheWorkspaceServiceTemplateApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceTemplateName = null;
            //var response = instance.GetUserResourceTemplatesApplicableToTheWorkspaceServiceTemplateApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesGet(serviceTemplateName);
            //Assert.IsType<ResourceTemplateInformationInList>(response);
        }

        /// <summary>
        /// Test RegisterUserResourceTemplateApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesPost
        /// </summary>
        [Fact]
        public void RegisterUserResourceTemplateApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceTemplateName = null;
            //UserResourceTemplateInCreate userResourceTemplateInCreate = null;
            //var response = instance.RegisterUserResourceTemplateApiWorkspaceServiceTemplatesServiceTemplateNameUserResourceTemplatesPost(serviceTemplateName, userResourceTemplateInCreate);
            //Assert.IsType<UserResourceTemplateInResponse>(response);
        }
    }
}
