/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TRE.Rest.Client.Client;
using TRE.Rest.Client.Api;
// uncomment below to import models
//using TRE.Rest.Client.Model;

namespace TRE.Rest.Client.Test.Api
{
    /// <summary>
    ///  Class for testing WorkspaceTemplatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WorkspaceTemplatesApiTests : IDisposable
    {
        private WorkspaceTemplatesApi instance;

        public WorkspaceTemplatesApiTests()
        {
            instance = new WorkspaceTemplatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceTemplatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WorkspaceTemplatesApi
            //Assert.IsType<WorkspaceTemplatesApi>(instance);
        }

        /// <summary>
        /// Test GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet
        /// </summary>
        [Fact]
        public void GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workspaceTemplateName = null;
            //bool? isUpdate = null;
            //var response = instance.GetWorkspaceTemplateByNameApiWorkspaceTemplatesWorkspaceTemplateNameGet(workspaceTemplateName, isUpdate);
            //Assert.IsType<WorkspaceTemplateInResponse>(response);
        }

        /// <summary>
        /// Test GetWorkspaceTemplatesApiWorkspaceTemplatesGet
        /// </summary>
        [Fact]
        public void GetWorkspaceTemplatesApiWorkspaceTemplatesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetWorkspaceTemplatesApiWorkspaceTemplatesGet();
            //Assert.IsType<ResourceTemplateInformationInList>(response);
        }

        /// <summary>
        /// Test RegisterWorkspaceTemplateApiWorkspaceTemplatesPost
        /// </summary>
        [Fact]
        public void RegisterWorkspaceTemplateApiWorkspaceTemplatesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WorkspaceTemplateInCreate workspaceTemplateInCreate = null;
            //var response = instance.RegisterWorkspaceTemplateApiWorkspaceTemplatesPost(workspaceTemplateInCreate);
            //Assert.IsType<WorkspaceTemplateInResponse>(response);
        }
    }
}
