/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using TRE.Rest.Client.Client;
using TRE.Rest.Client.Api;
// uncomment below to import models
//using TRE.Rest.Client.Model;

namespace TRE.Rest.Client.Test.Api
{
    /// <summary>
    ///  Class for testing WorkspaceServiceTemplatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WorkspaceServiceTemplatesApiTests : IDisposable
    {
        private WorkspaceServiceTemplatesApi instance;

        public WorkspaceServiceTemplatesApiTests()
        {
            instance = new WorkspaceServiceTemplatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceServiceTemplatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WorkspaceServiceTemplatesApi
            //Assert.IsType<WorkspaceServiceTemplatesApi>(instance);
        }

        /// <summary>
        /// Test GetWorkspaceServiceTemplateByNameApiWorkspaceServiceTemplatesServiceTemplateNameGet
        /// </summary>
        [Fact]
        public void GetWorkspaceServiceTemplateByNameApiWorkspaceServiceTemplatesServiceTemplateNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceTemplateName = null;
            //bool? isUpdate = null;
            //var response = instance.GetWorkspaceServiceTemplateByNameApiWorkspaceServiceTemplatesServiceTemplateNameGet(serviceTemplateName, isUpdate);
            //Assert.IsType<WorkspaceServiceTemplateInResponse>(response);
        }

        /// <summary>
        /// Test GetWorkspaceServiceTemplatesApiWorkspaceServiceTemplatesGet
        /// </summary>
        [Fact]
        public void GetWorkspaceServiceTemplatesApiWorkspaceServiceTemplatesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetWorkspaceServiceTemplatesApiWorkspaceServiceTemplatesGet();
            //Assert.IsType<ResourceTemplateInformationInList>(response);
        }

        /// <summary>
        /// Test RegisterWorkspaceServiceTemplateApiWorkspaceServiceTemplatesPost
        /// </summary>
        [Fact]
        public void RegisterWorkspaceServiceTemplateApiWorkspaceServiceTemplatesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //WorkspaceServiceTemplateInCreate workspaceServiceTemplateInCreate = null;
            //var response = instance.RegisterWorkspaceServiceTemplateApiWorkspaceServiceTemplatesPost(workspaceServiceTemplateInCreate);
            //Assert.IsType<WorkspaceServiceTemplateInResponse>(response);
        }
    }
}
