/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Operation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Operation
        //private Operation instance;

        public OperationTests()
        {
            // TODO uncomment below to create an instance of Operation
            //instance = new Operation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Operation
        /// </summary>
        [Fact]
        public void OperationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Operation
            //Assert.IsType<Operation>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Fact]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }
        /// <summary>
        /// Test the property 'ResourcePath'
        /// </summary>
        [Fact]
        public void ResourcePathTest()
        {
            // TODO unit test for the property 'ResourcePath'
        }
        /// <summary>
        /// Test the property 'ResourceVersion'
        /// </summary>
        [Fact]
        public void ResourceVersionTest()
        {
            // TODO unit test for the property 'ResourceVersion'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'CreatedWhen'
        /// </summary>
        [Fact]
        public void CreatedWhenTest()
        {
            // TODO unit test for the property 'CreatedWhen'
        }
        /// <summary>
        /// Test the property 'UpdatedWhen'
        /// </summary>
        [Fact]
        public void UpdatedWhenTest()
        {
            // TODO unit test for the property 'UpdatedWhen'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
