/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ResourceTemplateInformationInList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceTemplateInformationInListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceTemplateInformationInList
        //private ResourceTemplateInformationInList instance;

        public ResourceTemplateInformationInListTests()
        {
            // TODO uncomment below to create an instance of ResourceTemplateInformationInList
            //instance = new ResourceTemplateInformationInList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceTemplateInformationInList
        /// </summary>
        [Fact]
        public void ResourceTemplateInformationInListInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResourceTemplateInformationInList
            //Assert.IsType<ResourceTemplateInformationInList>(instance);
        }


        /// <summary>
        /// Test the property 'Templates'
        /// </summary>
        [Fact]
        public void TemplatesTest()
        {
            // TODO unit test for the property 'Templates'
        }

    }

}
