/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ResourceType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceType
        //private ResourceType instance;

        public ResourceTypeTests()
        {
            // TODO uncomment below to create an instance of ResourceType
            //instance = new ResourceType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceType
        /// </summary>
        [Fact]
        public void ResourceTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResourceType
            //Assert.IsType<ResourceType>(instance);
        }



    }

}
