/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ResourceHistoryItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceHistoryItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceHistoryItem
        //private ResourceHistoryItem instance;

        public ResourceHistoryItemTests()
        {
            // TODO uncomment below to create an instance of ResourceHistoryItem
            //instance = new ResourceHistoryItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceHistoryItem
        /// </summary>
        [Fact]
        public void ResourceHistoryItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResourceHistoryItem
            //Assert.IsType<ResourceHistoryItem>(instance);
        }


        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'ResourceVersion'
        /// </summary>
        [Fact]
        public void ResourceVersionTest()
        {
            // TODO unit test for the property 'ResourceVersion'
        }
        /// <summary>
        /// Test the property 'UpdatedWhen'
        /// </summary>
        [Fact]
        public void UpdatedWhenTest()
        {
            // TODO unit test for the property 'UpdatedWhen'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
