/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SharedService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharedServiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharedService
        //private SharedService instance;

        public SharedServiceTests()
        {
            // TODO uncomment below to create an instance of SharedService
            //instance = new SharedService();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharedService
        /// </summary>
        [Fact]
        public void SharedServiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharedService
            //Assert.IsType<SharedService>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TemplateName'
        /// </summary>
        [Fact]
        public void TemplateNameTest()
        {
            // TODO unit test for the property 'TemplateName'
        }
        /// <summary>
        /// Test the property 'TemplateVersion'
        /// </summary>
        [Fact]
        public void TemplateVersionTest()
        {
            // TODO unit test for the property 'TemplateVersion'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
        /// <summary>
        /// Test the property 'Etag'
        /// </summary>
        [Fact]
        public void EtagTest()
        {
            // TODO unit test for the property 'Etag'
        }
        /// <summary>
        /// Test the property 'ResourcePath'
        /// </summary>
        [Fact]
        public void ResourcePathTest()
        {
            // TODO unit test for the property 'ResourcePath'
        }
        /// <summary>
        /// Test the property 'ResourceVersion'
        /// </summary>
        [Fact]
        public void ResourceVersionTest()
        {
            // TODO unit test for the property 'ResourceVersion'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'UpdatedWhen'
        /// </summary>
        [Fact]
        public void UpdatedWhenTest()
        {
            // TODO unit test for the property 'UpdatedWhen'
        }
        /// <summary>
        /// Test the property 'History'
        /// </summary>
        [Fact]
        public void HistoryTest()
        {
            // TODO unit test for the property 'History'
        }

    }

}
