/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserResourceTemplateInResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserResourceTemplateInResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserResourceTemplateInResponse
        //private UserResourceTemplateInResponse instance;

        public UserResourceTemplateInResponseTests()
        {
            // TODO uncomment below to create an instance of UserResourceTemplateInResponse
            //instance = new UserResourceTemplateInResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserResourceTemplateInResponse
        /// </summary>
        [Fact]
        public void UserResourceTemplateInResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserResourceTemplateInResponse
            //Assert.IsType<UserResourceTemplateInResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }
        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Fact]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'CustomActions'
        /// </summary>
        [Fact]
        public void CustomActionsTest()
        {
            // TODO unit test for the property 'CustomActions'
        }
        /// <summary>
        /// Test the property 'Pipeline'
        /// </summary>
        [Fact]
        public void PipelineTest()
        {
            // TODO unit test for the property 'Pipeline'
        }
        /// <summary>
        /// Test the property 'AdditionalProperties'
        /// </summary>
        [Fact]
        public void AdditionalPropertiesTest()
        {
            // TODO unit test for the property 'AdditionalProperties'
        }
        /// <summary>
        /// Test the property 'SystemProperties'
        /// </summary>
        [Fact]
        public void SystemPropertiesTest()
        {
            // TODO unit test for the property 'SystemProperties'
        }
        /// <summary>
        /// Test the property 'ParentWorkspaceService'
        /// </summary>
        [Fact]
        public void ParentWorkspaceServiceTest()
        {
            // TODO unit test for the property 'ParentWorkspaceService'
        }

    }

}
