/*
 * Azure TRE API
 *
 * Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)
 *
 * The version of the OpenAPI document: 0.2.14
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TRE.Rest.Client.Api;
using TRE.Rest.Client.Model;
using TRE.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TRE.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceTemplateInCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkspaceTemplateInCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkspaceTemplateInCreate
        //private WorkspaceTemplateInCreate instance;

        public WorkspaceTemplateInCreateTests()
        {
            // TODO uncomment below to create an instance of WorkspaceTemplateInCreate
            //instance = new WorkspaceTemplateInCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceTemplateInCreate
        /// </summary>
        [Fact]
        public void WorkspaceTemplateInCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkspaceTemplateInCreate
            //Assert.IsType<WorkspaceTemplateInCreate>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Fact]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }
        /// <summary>
        /// Test the property 'JsonSchema'
        /// </summary>
        [Fact]
        public void JsonSchemaTest()
        {
            // TODO unit test for the property 'JsonSchema'
        }
        /// <summary>
        /// Test the property 'CustomActions'
        /// </summary>
        [Fact]
        public void CustomActionsTest()
        {
            // TODO unit test for the property 'CustomActions'
        }

    }

}
